# -*- coding: utf-8 -*-
"""e274020_DI725_assignment1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASm4417nfVmBKFoQZ48nFa4HjWwQBWHR

# **WANDB Connection**
"""

!pip install wandb

import wandb
wandb.login()

wandb.init(
    project="sentiment-analysis-assignment",
    name="roberta-class-weighted"
)

"""# **Libraries**"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px
import plotly.graph_objects as go

import torch
from torch import nn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from transformers import RobertaTokenizer, RobertaForSequenceClassification, Trainer, TrainingArguments

warnings.filterwarnings('ignore')

"""# **Exploratory Data Analysis**"""

df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

print("df_train shape", df_train.shape)
print("df_test shape", df_test.shape)

df_train.isnull().sum()

df_test.isnull().sum()

df_train.head(3)

df_train.columns

df_train['customer_sentiment'].value_counts()

pd.crosstab(df_train["issue_area"], df_train["customer_sentiment"])

sentiment_counts = df_train['customer_sentiment'].value_counts().reset_index()
sentiment_counts.columns = ['customer_sentiment', 'count']

fig = px.pie(
    sentiment_counts,
    names='customer_sentiment',
    values='count',
    title='Customer Sentiment Distribution'
)
fig.show()

df_train['word_count'] = df_train['conversation'].apply(lambda x: len(str(x).split()))
df_train['char_length'] = df_train['conversation'].str.len()

# 1. Text Length Distribution (Histogram)
fig1 = px.histogram(df_train, x='word_count', nbins=50,
                   title='Konuşma Uzunluğu (Kelime Sayısı) Dağılımı',
                   labels={'word_count': 'Kelime Sayısı'},
                   color_discrete_sequence=['#636EFA'])
fig1.show()

# 2. The Relationship Between Emotion and Text Length (Box Plot)
# Answers the question: ‘Are negative comments longer?’
fig2 = px.box(df_train, x='customer_sentiment', y='word_count',
             color='customer_sentiment',
             title='Duygu Sınıflarına Göre Kelime Sayısı Dağılımı',
             labels={'customer_sentiment': 'Duygu', 'word_count': 'Kelime Sayısı'})
fig2.show()

# 3. Issue Area and Sentiment Correlation (Stacked Bar)
# Which departments have higher levels of negative sentiment?
issue_sentiment = df_train.groupby(['issue_area', 'customer_sentiment']).size().reset_index(name='count')
fig3 = px.bar(issue_sentiment, x='issue_area', y='count', color='customer_sentiment',
             title='Departman Bazlı Duygu Dağılımı',
             labels={'issue_area': 'Konu Alanı', 'count': 'Adet'},
             barmode='stack')
fig3.update_layout(xaxis={'categoryorder':'total descending'})
fig3.show()

issue_complexity = df_train.groupby(['issue_complexity', 'customer_sentiment']).size().reset_index(name='count')
fig4 = px.bar(issue_complexity, x='issue_complexity', y='count', color='customer_sentiment',
             title='Distribution of Customer Sentiment over Issue Complexity',
             labels={'issue_complexity': 'Issue Complexity', 'count': 'Count'},
             barmode='stack')
fig4.update_layout(xaxis={'categoryorder':'total descending'})
fig4.show()

"""# **Cleaning**

Reducing the number of token because the models has limited token numbers.
"""

df_train["conversation"][20]

df_train["conversation"][250]

def clean_intro(text):
    text = text.lower()
    pattern = r"agent:\s*(?:hello|hi)?[.,]?\s*thank you for (?:calling|contacting) brownbox customer support[.,]?\s*my name is .*?\.\s*how (?:can|may) i assist you today\?\s*customer:\s*"
    cleaned_text = re.sub(pattern, "", text)
    return cleaned_text.strip()

def clean_newlines(text):
  text= text.replace('\n',' ')
  text = re.sub(r'\s+', ' ', text)
  return text.strip()

def clean_system_notes(text):
  cleaned_text = re.sub(r'\s*\(.*?\)\s*', ' ', text)
  cleaned_text = re.sub(r'\s+', ' ', cleaned_text)
  cleaned_text = re.sub(r'\[.*?\]', '', cleaned_text)
  return cleaned_text.strip()


df_train['conversation'] = df_train['conversation'].apply(clean_intro)
df_train['conversation'] = df_train['conversation'].apply(clean_newlines)
df_train['conversation'] = df_train['conversation'].apply(clean_system_notes)

df_train["conversation"][250]

"""# **Class Weights**"""

df_train["customer_sentiment"].unique()[1]

label_map = {label: idx for idx, label in enumerate(df_train["customer_sentiment"].unique())}
label_map

df_train['label'] = df_train['customer_sentiment'].map(label_map)
df_train.head(2)

"""# **Roberta**"""

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(df_train["label"]),
    y=df_train["label"]
)

class_weights = torch.tensor(class_weights, dtype=torch.float)
class_weights

from transformers import AutoTokenizer # Added this import

tokenizer = AutoTokenizer.from_pretrained("roberta-base")

def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

train_df = df_train[["conversation", "label"]]
test_df = df_test[["conversation"]]

train_df, val_df = train_test_split(
    df_train,
    test_size=0.2,
    stratify=df_train["label"],
    random_state=42
)

from datasets import Dataset

# Rename 'conversation' column to 'text' for tokenization
train_df_processed = train_df.rename(columns={'conversation': 'text'})
val_df_processed = val_df.rename(columns={'conversation': 'text'})
df_test_processed = df_test.rename(columns={'conversation': 'text'})

train_dataset = Dataset.from_pandas(train_df_processed)
val_dataset = Dataset.from_pandas(val_df_processed)
test_dataset = Dataset.from_pandas(df_test_processed)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

from transformers import AutoModelForSequenceClassification # Added this import

model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels=3
)

device = "cuda" if torch.cuda.is_available() else "cpu"
class_weights = class_weights.to(device)

loss_fn = CrossEntropyLoss(weight=class_weights)
class CustomTrainer(HFTrainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None): # Added num_items_in_batch
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss = loss_fn(logits, labels)

        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="weighted"
    )
    acc = accuracy_score(labels, preds)

    wandb.log({
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall,
        "confusion_matrix": wandb.plot.confusion_matrix(
            probs=None,
            y_true=labels,
            preds=preds,
            class_names=["neg", "neu", "pos"]
        )
    })

    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=10,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,

    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="f1",

    logging_strategy="steps",
    logging_steps=50,

    report_to="wandb",
    run_name="roberta-sentiment-analysis",

    warmup_ratio=0.1,
    seed=42
)

from transformers import EarlyStoppingCallback
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()

